# Sniperkit-Bot
# - Status: analyzed

apiVersion: v1
kind: ReplicationController
metadata:
  name: sandbox
  labels:
    name: sandbox
spec:
  replicas: 3
  selector:
    name: sandbox
  template:
    metadata:
      labels:
        name: sandbox
    spec:
      containers:
      - name: sandbox
        image: sniperkit/snk.fork.pachyderm-sandbox
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 9080
