# Sniperkit-Bot
# - Status: analyzed

apiVersion: v1
kind: Service
metadata:
  name: sandbox
  labels:
    name: sandbox
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9080
  selector:
    name: sandbox